// src/app/CopyField.tsx
import { useState } from 'react';
import { copyText } from '../lib/util';

interface Props {
  label: string;
  value: string;
  rows?: number;
  hint?: string;
}

export default function CopyField({ label, value, rows = 1, hint }: Props) {
  const [copied, setCopied] = useState(false);

  async function copy() {
    setCopied(await copyText(value));
    setTimeout(() => setCopied(false), 1500);
  }

  const select = (e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => e.currentTarget.select();

  return (
    <div className="copy-field">
      <div className="copy-field-head">
        <strong>{label}</strong>
        <button className="btn small" onClick={copy}>
          {copied ? '已复制 ✓' : '复制'}
        </button>
      </div>
      {rows > 1 ? (
        <textarea className="input mono" readOnly rows={rows} value={value} onFocus={select} />
      ) : (
        <input className="input mono" readOnly value={value} onFocus={select} />
      )}
      {hint && <small className="muted">{hint}</small>}
    </div>
  );
}

// src/app/CopyField.svelte
<script lang="ts">
  import { copyText } from '../lib/util';

  interface Props {
    label: string;
    value: string;
    rows?: number;
    hint?: string;
  }
  let { label, value, rows = 1, hint }: Props = $props();
  let copied = $state(false);

  async function copy() {
    copied = await copyText(value);
    setTimeout(() => (copied = false), 1500);
  }
</script>

<div class="field">
  <div class="head">
    <strong>{label}</strong>
    <button class="btn small" onclick={copy}>{copied ? '已复制 ✓' : '复制'}</button>
  </div>
  {#if rows > 1}
    <textarea class="input" readonly {rows} {value} onfocus={(e) => e.currentTarget.select()}></textarea>
  {:else}
    <input class="input" readonly {value} onfocus={(e) => e.currentTarget.select()} />
  {/if}
  {#if hint}<small class="muted">{hint}</small>{/if}
</div>

<style>
  .field {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .head {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  input.input {
    width: 100%;
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 0.8rem;
  }
</style>
