// src/app/DrawDialog.tsx
import { useState } from 'react';
import CardImage from '../components/CardImage';
import CardZoom from '../components/CardZoom';
import { shuffle } from '../lib/util';
import Modal from './Modal';
import { lookup, useLimitOf, useStore } from './store';

function deal(main: number[], second: boolean) {
  const pile = shuffle(main);
  const hand = pile.splice(0, second ? 6 : 5);
  return { pile, hand };
}

export default function DrawDialog({ onClose }: { onClose: () => void }) {
  const main = useStore((s) => s.deck.main);
  const setnames = useStore((s) => s.setnames);
  const limitOf = useLimitOf();
  const [second, setSecond] = useState(false);
  const [state, setState] = useState(() => deal(main, false));
  const [zoom, setZoom] = useState<number | null>(null);

  function drawOne() {
    const [next, ...rest] = state.pile;
    if (next !== undefined) setState({ pile: rest, hand: [...state.hand, next] });
  }

  return (
    <Modal title="试抽起手" onClose={onClose} wide>
      <div className="row">
        <label>
          <input
            type="checkbox"
            checked={second}
            onChange={(e) => {
              setSecond(e.target.checked);
              setState(deal(main, e.target.checked));
            }}
          />{' '}
          后攻（6 张）
        </label>
        <button className="btn primary" onClick={() => setState(deal(main, second))} disabled={!main.length}>
          重新洗切
        </button>
        <button className="btn" onClick={drawOne} disabled={!state.pile.length}>
          再抽一张
        </button>
        <span className="muted">卡组剩余 {state.pile.length}</span>
      </div>
      {state.hand.length ? (
        <div className="hand">
          {state.hand.map((id, i) => (
            <button key={i} className="ygo-deck-cell" onClick={() => setZoom(i)}>
              <CardImage id={id} card={lookup(id)} lazy={false} />
            </button>
          ))}
        </div>
      ) : (
        <p className="muted">主卡组是空的。</p>
      )}
      {zoom !== null && (
        <CardZoom ids={state.hand} index={zoom} onIndexChange={setZoom} lookup={lookup} setnames={setnames} limitOf={limitOf} onClose={() => setZoom(null)} />
      )}
    </Modal>
  );
}

// src/app/DrawDialog.svelte
<script lang="ts">
  import Modal from '../components/Modal.svelte';
  import CardImage from '../components/CardImage.svelte';
  import CardZoom from '../components/CardZoom.svelte';
  import { shuffle } from '../lib/util';
  import { app, db, limitOf, lookup } from './state.svelte';

  let { onclose }: { onclose: () => void } = $props();
  let second = $state(false);
  let pile = $state<number[]>([]);
  let hand = $state<number[]>([]);
  let zoom = $state<number | null>(null);

  function deal() {
    pile = shuffle(app.deck.main);
    hand = pile.splice(0, second ? 6 : 5);
  }
  function drawOne() {
    const c = pile.shift();
    if (c !== undefined) hand.push(c);
  }
  deal();
</script>

<Modal title="试抽起手" {onclose} wide>
  <div class="bar">
    <label><input type="checkbox" bind:checked={second} onchange={deal} /> 后攻（6 张）</label>
    <button class="btn primary" onclick={deal} disabled={!app.deck.main.length}>重新洗切</button>
    <button class="btn" onclick={drawOne} disabled={!pile.length}>再抽一张</button>
    <span class="muted">卡组剩余 {pile.length}</span>
  </div>
  {#if hand.length}
    <div class="hand">
      {#each hand as id, i (i)}
        <button class="cell" onclick={() => (zoom = i)}><CardImage {id} card={lookup(id)} lazy={false} /></button>
      {/each}
    </div>
  {:else}
    <p class="muted">主卡组是空的。</p>
  {/if}
</Modal>

{#if zoom !== null}
  <CardZoom ids={hand} bind:index={zoom} {lookup} setnames={db.setnames} {limitOf} onclose={() => (zoom = null)} />
{/if}

<style>
  .bar {
    display: flex;
    gap: 10px;
    align-items: center;
    flex-wrap: wrap;
  }
  .hand {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(110px, 1fr));
    gap: 8px;
  }
  .cell {
    padding: 0;
    border: 0;
    background: none;
    cursor: zoom-in;
  }
</style>
