// src/app/SearchPanel.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import CardImage from '../components/CardImage';
import { ATTRIBUTES, RACES, TYPE, attributeLabel, isLink, isMonster, levelLabel, raceLabel, statLabel, typeLabel } from '../lib/card';
import { defaultQuery, search, type Kind, type SearchQuery, type SortKey } from '../lib/search';
import { DRAG_TYPE, readDrag, writeDrag } from './drag';
import { addCard, removeAt, select, selectBanlist, useLimitOf, useStore } from './store';

const PAGE = 60;

const KINDS: [Kind, string][] = [
  ['all', '全部'],
  ['monster', '怪兽'],
  ['spell', '魔法'],
  ['trap', '陷阱'],
];

const SUBTYPES: Record<Kind, [number, string][]> = {
  all: [],
  monster: [
    [TYPE.NORMAL, '通常'],
    [TYPE.EFFECT, '效果'],
    [TYPE.RITUAL, '仪式'],
    [TYPE.FUSION, '融合'],
    [TYPE.SYNCHRO, '同调'],
    [TYPE.XYZ, '超量'],
    [TYPE.LINK, '连接'],
    [TYPE.PENDULUM, '灵摆'],
    [TYPE.TUNER, '调整'],
    [TYPE.FLIP, '反转'],
    [TYPE.SPIRIT, '灵魂'],
    [TYPE.UNION, '同盟'],
    [TYPE.GEMINI, '二重'],
    [TYPE.TOON, '卡通'],
    [TYPE.SPSUMMON, '特殊召唤'],
  ],
  spell: [
    [TYPE.QUICKPLAY, '速攻'],
    [TYPE.CONTINUOUS, '永续'],
    [TYPE.EQUIP, '装备'],
    [TYPE.FIELD, '场地'],
    [TYPE.RITUAL, '仪式'],
  ],
  trap: [
    [TYPE.CONTINUOUS, '永续'],
    [TYPE.COUNTER, '反击'],
  ],
};

const SORTS: [SortKey, string][] = [
  ['relevance', '相关度'],
  ['id', '卡号'],
  ['name', '名称'],
  ['level', '等级'],
  ['atk', '攻击力'],
  ['def', '守备力'],
];

const numOrNull = (v: string) => (v.trim() === '' ? null : Number(v));

function Range({ label, min, max, step, onMin, onMax }: { label: string; min: number | null; max: number | null; step?: number; onMin: (v: number | null) => void; onMax: (v: number | null) => void }) {
  return (
    <label>
      {label}
      <span className="range">
        <input className="input" type="number" step={step} placeholder="最小" value={min ?? ''} onChange={(e) => onMin(numOrNull(e.target.value))} />
        <input className="input" type="number" step={step} placeholder="最大" value={max ?? ''} onChange={(e) => onMax(numOrNull(e.target.value))} />
      </span>
    </label>
  );
}

export default function SearchPanel() {
  const cards = useStore((s) => s.cards);
  const setnames = useStore((s) => s.setnames);
  const loading = useStore((s) => s.loading);
  const selected = useStore((s) => s.selected);
  const banlist = useStore(selectBanlist);
  const limitOf = useLimitOf();

  const [q, setQ] = useState<SearchQuery>(defaultQuery);
  const [text, setText] = useState('');
  const [setnameInput, setSetnameInput] = useState('');
  const [showFilters, setShowFilters] = useState(false);
  const [pageSize, setPageSize] = useState(PAGE);
  const [dropping, setDropping] = useState(false);
  const patch = (p: Partial<SearchQuery>) => {
    setQ((old) => ({ ...old, ...p }));
    setPageSize(PAGE);
  };

  // 输入防抖
  useEffect(() => {
    const t = setTimeout(() => patch({ text }), 150);
    return () => clearTimeout(t);
  }, [text]);

  const { setnameList, setnameByName } = useMemo(() => {
    const byName = new Map<string, number[]>();
    for (const [code, name] of setnames) byName.set(name, [...(byName.get(name) ?? []), code]);
    return { setnameList: [...byName.keys()], setnameByName: byName };
  }, [setnames]);

  useEffect(() => {
    patch({ setcodes: setnameByName.get(setnameInput.trim()) ?? [] });
  }, [setnameInput, setnameByName]);

  const results = useMemo(() => search(cards, q, banlist), [cards, q, banlist]);
  const shown = results.slice(0, pageSize);

  // 滚动到底部时加载更多
  const sentinel = useRef<HTMLLIElement>(null);
  useEffect(() => {
    const el = sentinel.current;
    if (!el) return;
    const io = new IntersectionObserver((entries) => {
      if (entries[0].isIntersecting) setPageSize((n) => (n < results.length ? n + PAGE : n));
    });
    io.observe(el);
    return () => io.disconnect();
  }, [results]);

  function reset() {
    setQ(defaultQuery());
    setText('');
    setSetnameInput('');
    setPageSize(PAGE);
  }

  return (
    <div
      className={dropping ? 'search-panel dropping' : 'search-panel'}
      onDragOver={(e) => {
        if (e.dataTransfer.types.includes(DRAG_TYPE)) {
          e.preventDefault();
          setDropping(true);
        }
      }}
      onDragLeave={() => setDropping(false)}
      onDrop={(e) => {
        // 从卡组拖回搜索栏 = 移出卡组
        setDropping(false);
        const d = readDrag(e.nativeEvent);
        if (d && d.from !== 'search') {
          e.preventDefault();
          removeAt(d.from, d.index);
        }
      }}
    >
      <input className="input search" type="search" placeholder="搜索卡名 / 效果 / 卡号，空格分隔多个关键词" value={text} onChange={(e) => setText(e.target.value)} />
      <div className="kinds">
        {KINDS.map(([k, label]) => (
          <button key={k} className={q.kind === k ? 'seg on' : 'seg'} onClick={() => patch({ kind: k, subtype: 0 })}>
            {label}
          </button>
        ))}
        <button className="btn small" onClick={() => setShowFilters(!showFilters)}>
          筛选 {showFilters ? '▴' : '▾'}
        </button>
      </div>

      {showFilters && (
        <div className="filters">
          {SUBTYPES[q.kind].length > 0 && (
            <label>
              类型
              <select className="input" value={q.subtype} onChange={(e) => patch({ subtype: Number(e.target.value) })}>
                <option value={0}>不限</option>
                {SUBTYPES[q.kind].map(([bit, label]) => (
                  <option key={bit} value={bit}>
                    {label}
                  </option>
                ))}
              </select>
            </label>
          )}
          <label>
            属性
            <select className="input" value={q.attribute} onChange={(e) => patch({ attribute: Number(e.target.value) })}>
              <option value={0}>不限</option>
              {ATTRIBUTES.map(([bit, label]) => (
                <option key={bit} value={bit}>
                  {label}
                </option>
              ))}
            </select>
          </label>
          <label>
            种族
            <select className="input" value={q.race} onChange={(e) => patch({ race: Number(e.target.value) })}>
              <option value={0}>不限</option>
              {RACES.map(([bit, label]) => (
                <option key={bit} value={bit}>
                  {label}族
                </option>
              ))}
            </select>
          </label>
          <label>
            字段
            <input className="input" list="ygo-setnames" placeholder="输入系列名" value={setnameInput} onChange={(e) => setSetnameInput(e.target.value)} />
            <datalist id="ygo-setnames">
              {setnameList.map((name) => (
                <option key={name} value={name} />
              ))}
            </datalist>
          </label>
          <Range label="等级/阶级/连接" min={q.levelMin} max={q.levelMax} onMin={(v) => patch({ levelMin: v })} onMax={(v) => patch({ levelMax: v })} />
          <Range label="攻击力" step={100} min={q.atkMin} max={q.atkMax} onMin={(v) => patch({ atkMin: v })} onMax={(v) => patch({ atkMax: v })} />
          <Range label="守备力" step={100} min={q.defMin} max={q.defMax} onMin={(v) => patch({ defMin: v })} onMax={(v) => patch({ defMax: v })} />
          <label>
            禁限
            <select className="input" value={q.limit} onChange={(e) => patch({ limit: Number(e.target.value) })}>
              <option value={-1}>不限</option>
              <option value={0}>禁止</option>
              <option value={1}>限制</option>
              <option value={2}>准限制</option>
            </select>
          </label>
          <label>
            地区
            <select className="input" value={q.ot} onChange={(e) => patch({ ot: Number(e.target.value) })}>
              <option value={0}>不限</option>
              <option value={1}>OCG</option>
              <option value={2}>TCG</option>
              <option value={8}>简中</option>
            </select>
          </label>
          <label>
            排序
            <select className="input" value={q.sort} onChange={(e) => patch({ sort: e.target.value as SortKey })}>
              {SORTS.map(([k, label]) => (
                <option key={k} value={k}>
                  {label}
                </option>
              ))}
            </select>
          </label>
          <label className="check">
            <input type="checkbox" checked={q.altArt} onChange={(e) => patch({ altArt: e.target.checked })} /> 显示异画卡
          </label>
          <button className="btn small" onClick={reset}>
            重置条件
          </button>
        </div>
      )}

      <div className="count muted">
        {loading ? '加载卡片数据…' : `共 ${results.length} 张`}
        <span className="hint">单击查看 · 双击或 + 加入卡组 · 可拖动</span>
      </div>

      <ul className="results">
        {shown.map((card) => (
          <li key={card.id} className={selected === card.id ? 'selected' : undefined} draggable onDragStart={(e) => writeDrag(e.nativeEvent, { from: 'search', index: -1, id: card.id })}>
            <button className="row" onClick={() => select(card.id)} onDoubleClick={() => addCard(card.id)}>
              <span className="thumb">
                <CardImage id={card.id} card={card} limit={limitOf(card)} />
              </span>
              <span className="info">
                <span className="name">{card.name}</span>
                <span className="line">
                  {typeLabel(card)}
                  {isMonster(card) && ` · ${attributeLabel(card)} · ${raceLabel(card)}`}
                </span>
                {isMonster(card) && (
                  <span className="line">
                    {levelLabel(card)} · {statLabel(card.atk)}
                    {isLink(card) ? '' : ` / ${statLabel(card.def)}`}
                  </span>
                )}
              </span>
            </button>
            <span className="add">
              <button className="btn small" title="加入主卡组 / 额外卡组" onClick={() => addCard(card.id)}>
                +
              </button>
              <button className="btn small" title="加入副卡组" onClick={() => addCard(card.id, 'side')}>
                副
              </button>
            </span>
          </li>
        ))}
        <li className="sentinel" ref={sentinel} />
      </ul>
    </div>
  );
}

// src/app/SearchPanel.svelte
<script lang="ts">
  import { ATTRIBUTES, RACES, TYPE, isMonster, isLink, levelLabel, statLabel, typeLabel, attributeLabel, raceLabel } from '../lib/card';
  import { defaultQuery, search, type SearchQuery, type SortKey } from '../lib/search';
  import CardImage from '../components/CardImage.svelte';
  import { addCard, app, currentBanlist, db, limitOf, removeAt } from './state.svelte';
  import { DRAG_TYPE, readDrag, writeDrag } from './drag';

  let q = $state<SearchQuery>(defaultQuery());
  let text = $state('');
  let showFilters = $state(false);
  let setnameInput = $state('');
  let pageSize = $state(60);
  let dropping = $state(false);

  // 输入防抖
  $effect(() => {
    const t = text;
    const timer = setTimeout(() => (q.text = t), 150);
    return () => clearTimeout(timer);
  });

  const setnameList = $derived([...new Set(db.setnames.values())]);
  const setnameByName = $derived.by(() => {
    const m = new Map<string, number[]>();
    for (const [code, name] of db.setnames) m.set(name, [...(m.get(name) ?? []), code]);
    return m;
  });
  $effect(() => {
    q.setcodes = setnameByName.get(setnameInput.trim()) ?? [];
  });

  const results = $derived(search(db.cards, q, currentBanlist()));
  const shown = $derived(results.slice(0, pageSize));

  $effect(() => {
    // 条件变化时回到第一页
    JSON.stringify(q);
    pageSize = 60;
  });

  const SUBTYPES: Record<string, [number, string][]> = {
    all: [],
    monster: [
      [TYPE.NORMAL, '通常'],
      [TYPE.EFFECT, '效果'],
      [TYPE.RITUAL, '仪式'],
      [TYPE.FUSION, '融合'],
      [TYPE.SYNCHRO, '同调'],
      [TYPE.XYZ, '超量'],
      [TYPE.LINK, '连接'],
      [TYPE.PENDULUM, '灵摆'],
      [TYPE.TUNER, '调整'],
      [TYPE.FLIP, '反转'],
      [TYPE.SPIRIT, '灵魂'],
      [TYPE.UNION, '同盟'],
      [TYPE.GEMINI, '二重'],
      [TYPE.TOON, '卡通'],
      [TYPE.SPSUMMON, '特殊召唤'],
    ],
    spell: [
      [TYPE.QUICKPLAY, '速攻'],
      [TYPE.CONTINUOUS, '永续'],
      [TYPE.EQUIP, '装备'],
      [TYPE.FIELD, '场地'],
      [TYPE.RITUAL, '仪式'],
    ],
    trap: [
      [TYPE.CONTINUOUS, '永续'],
      [TYPE.COUNTER, '反击'],
    ],
  };

  function setKind(k: SearchQuery['kind']) {
    q.kind = k;
    q.subtype = 0;
  }

  function reset() {
    q = defaultQuery();
    text = '';
    setnameInput = '';
  }

  const numInput = (v: string) => (v.trim() === '' ? null : Number(v));

  let sentinel = $state<HTMLElement>();
  $effect(() => {
    if (!sentinel) return;
    const io = new IntersectionObserver((entries) => {
      if (entries[0].isIntersecting && pageSize < results.length) pageSize += 60;
    });
    io.observe(sentinel);
    return () => io.disconnect();
  });

  // 从卡组拖回搜索栏 = 移出卡组
  function ondrop(e: DragEvent) {
    dropping = false;
    const d = readDrag(e);
    if (d && d.from !== 'search') {
      e.preventDefault();
      removeAt(d.from, d.index);
    }
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  class="search-panel"
  class:dropping
  ondragover={(e) => {
    if (e.dataTransfer?.types.includes(DRAG_TYPE)) {
      e.preventDefault();
      dropping = true;
    }
  }}
  ondragleave={() => (dropping = false)}
  {ondrop}
>
  <div class="bar">
    <input class="input search" type="search" placeholder="搜索卡名 / 效果 / 卡号，空格分隔多个关键词" bind:value={text} />
  </div>
  <div class="bar kinds">
    {#each [['all', '全部'], ['monster', '怪兽'], ['spell', '魔法'], ['trap', '陷阱']] as [k, label] (k)}
      <button class="seg" class:on={q.kind === k} onclick={() => setKind(k as SearchQuery['kind'])}>{label}</button>
    {/each}
    <button class="btn small" class:on={showFilters} onclick={() => (showFilters = !showFilters)}>筛选{showFilters ? ' ▴' : ' ▾'}</button>
  </div>

  {#if showFilters}
    <div class="filters">
      {#if SUBTYPES[q.kind].length}
        <label>类型
          <select class="input" bind:value={q.subtype}>
            <option value={0}>不限</option>
            {#each SUBTYPES[q.kind] as [bit, label] (bit)}<option value={bit}>{label}</option>{/each}
          </select>
        </label>
      {/if}
      <label>属性
        <select class="input" bind:value={q.attribute}>
          <option value={0}>不限</option>
          {#each ATTRIBUTES as [bit, label] (bit)}<option value={bit}>{label}</option>{/each}
        </select>
      </label>
      <label>种族
        <select class="input" bind:value={q.race}>
          <option value={0}>不限</option>
          {#each RACES as [bit, label] (bit)}<option value={bit}>{label}族</option>{/each}
        </select>
      </label>
      <label>字段
        <input class="input" list="setnames" placeholder="输入系列名" bind:value={setnameInput} />
        <datalist id="setnames">
          {#each setnameList as name (name)}<option value={name}></option>{/each}
        </datalist>
      </label>
      <label>等级/阶级/连接
        <span class="range">
          <input class="input" type="number" min="0" max="13" placeholder="最小" value={q.levelMin ?? ''} oninput={(e) => (q.levelMin = numInput(e.currentTarget.value))} />
          <input class="input" type="number" min="0" max="13" placeholder="最大" value={q.levelMax ?? ''} oninput={(e) => (q.levelMax = numInput(e.currentTarget.value))} />
        </span>
      </label>
      <label>攻击力
        <span class="range">
          <input class="input" type="number" step="100" placeholder="最小" value={q.atkMin ?? ''} oninput={(e) => (q.atkMin = numInput(e.currentTarget.value))} />
          <input class="input" type="number" step="100" placeholder="最大" value={q.atkMax ?? ''} oninput={(e) => (q.atkMax = numInput(e.currentTarget.value))} />
        </span>
      </label>
      <label>守备力
        <span class="range">
          <input class="input" type="number" step="100" placeholder="最小" value={q.defMin ?? ''} oninput={(e) => (q.defMin = numInput(e.currentTarget.value))} />
          <input class="input" type="number" step="100" placeholder="最大" value={q.defMax ?? ''} oninput={(e) => (q.defMax = numInput(e.currentTarget.value))} />
        </span>
      </label>
      <label>禁限
        <select class="input" bind:value={q.limit}>
          <option value={-1}>不限</option>
          <option value={0}>禁止</option>
          <option value={1}>限制</option>
          <option value={2}>准限制</option>
        </select>
      </label>
      <label>地区
        <select class="input" bind:value={q.ot}>
          <option value={0}>不限</option>
          <option value={1}>OCG</option>
          <option value={2}>TCG</option>
          <option value={8}>简中</option>
        </select>
      </label>
      <label>排序
        <select class="input" bind:value={q.sort}>
          {#each [['relevance', '相关度'], ['id', '卡号'], ['name', '名称'], ['level', '等级'], ['atk', '攻击力'], ['def', '守备力']] as [k, label] (k)}
            <option value={k as SortKey}>{label}</option>
          {/each}
        </select>
      </label>
      <label class="check"><input type="checkbox" bind:checked={q.altArt} /> 显示异画卡</label>
      <button class="btn small" onclick={reset}>重置条件</button>
    </div>
  {/if}

  <div class="count muted">
    {#if app.loading}加载卡片数据…{:else}共 {results.length} 张{/if}
    <span class="hint">单击查看 · 双击或 + 加入卡组 · 可拖动</span>
  </div>

  <ul class="results">
    {#each shown as card (card.id)}
      {@const limit = limitOf(card)}
      <li
        class:selected={app.selected === card.id}
        draggable="true"
        ondragstart={(e) => writeDrag(e, { from: 'search', index: -1, id: card.id })}
      >
        <button class="row" onclick={() => (app.selected = card.id)} ondblclick={() => addCard(card.id)}>
          <span class="thumb"><CardImage id={card.id} {card} {limit} /></span>
          <span class="info">
            <span class="name">{card.name}</span>
            <span class="line">{typeLabel(card)}{#if isMonster(card)} · {attributeLabel(card)} · {raceLabel(card)}{/if}</span>
            {#if isMonster(card)}
              <span class="line">{levelLabel(card)} · {statLabel(card.atk)}{isLink(card) ? '' : ` / ${statLabel(card.def)}`}</span>
            {/if}
          </span>
        </button>
        <span class="add">
          <button class="btn small" title="加入主卡组 / 额外卡组" onclick={() => addCard(card.id)}>+</button>
          <button class="btn small" title="加入副卡组" onclick={() => addCard(card.id, 'side')}>副</button>
        </span>
      </li>
    {/each}
    <li class="sentinel" bind:this={sentinel}></li>
  </ul>
</div>

<style>
  .search-panel {
    display: flex;
    flex-direction: column;
    gap: 8px;
    min-height: 0;
    height: 100%;
  }
  .search-panel.dropping {
    outline: 2px dashed var(--danger);
    outline-offset: -2px;
  }
  .bar {
    display: flex;
    gap: 6px;
    align-items: center;
  }
  .search {
    flex: 1;
    padding: 8px 10px;
  }
  .kinds .seg {
    flex: 1;
    padding: 4px 0;
    border: 1px solid var(--border);
    background: var(--panel);
    border-radius: 6px;
    cursor: pointer;
  }
  .kinds .seg.on {
    background: var(--accent);
    border-color: var(--accent);
    color: var(--accent-contrast);
  }
  .filters {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 6px 10px;
    padding: 10px;
    background: var(--panel-2);
    border-radius: var(--radius);
    font-size: 0.82rem;
  }
  .filters label {
    display: flex;
    flex-direction: column;
    gap: 2px;
    min-width: 0;
  }
  .filters label.check {
    flex-direction: row;
    align-items: center;
    gap: 6px;
  }
  .range {
    display: flex;
    gap: 4px;
  }
  .range .input {
    width: 50%;
  }
  .count {
    display: flex;
    justify-content: space-between;
    gap: 8px;
    font-size: 0.8rem;
  }
  .results {
    list-style: none;
    margin: 0;
    padding: 0;
    overflow-y: auto;
    flex: 1;
    min-height: 0;
  }
  .results li {
    display: flex;
    align-items: center;
    border-bottom: 1px solid var(--border);
  }
  .results li.selected {
    background: color-mix(in srgb, var(--accent) 12%, transparent);
  }
  .row {
    flex: 1;
    display: flex;
    gap: 8px;
    padding: 5px 4px;
    border: 0;
    background: none;
    text-align: left;
    cursor: pointer;
    min-width: 0;
  }
  .thumb {
    width: 44px;
    flex: none;
  }
  .info {
    display: flex;
    flex-direction: column;
    min-width: 0;
  }
  .name {
    font-weight: 600;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .line {
    font-size: 0.78rem;
    color: var(--muted);
  }
  .add {
    display: flex;
    flex-direction: column;
    gap: 3px;
    padding-right: 4px;
  }
  .sentinel {
    height: 1px;
    border: 0 !important;
  }
  @media (max-width: 480px) {
    .hint {
      display: none;
    }
    .filters {
      grid-template-columns: 1fr;
    }
  }
</style>
